
const $=id=>document.getElementById(id), money=n=>'$'+Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2}), wait=ms=>new Promise(r=>setTimeout(r,ms));
let currentUser=null,currentSession=localStorage.getItem('donutmine_session')||'',staffSession=localStorage.getItem('donutmine_staff')||'',pendingAuthId=null,pendingDepositId=null,loginTimer=null,depositTimer=null,currentGame=null,currentFair=null,currentState=null,crashTimer=null,currentChoice=null;
const GAMES=[['DICE','Dice','1789026358094.png','classic','Choose a target and roll.'],['MINES','Mines','1789041604655.png','classic','Pick tiles. Avoid mines.'],['TOWER','Tower','1789044235777.png','classic','Choose a safe block each floor.'],['BLACKJACK','Blackjack','1789046522633.png','classic','Hit, stand or double.'],['RUSSIAN ROULETTE','Russian Roulette','1789046804299.png','classic','Choose a chamber. Pull.'],['CRASH','Crash','1789044604190.png','multiplayer','Ride the rocket. Cash out before crash.'],['DONUT ROULETTE','Donut Roulette','1789046804299.png','classic','Pick a pocket and spin.'],['STRIP MINE','Strip Mine','1789046640793.png','classic','Break blocks and hunt the vein.'],['CASE BATTLES','Case Battles','1789044447510.png','multiplayer','Open your case against the opponent.'],['LIMBO','Limbo','1789046990064.png','classic','Set a multiplier and jump.'],['KENO','Keno','1789044235777.png','classic','Pick numbers, then draw.'],['HI-LO','Hi-Lo','1789046522633.png','classic','Predict the next card.'],['SNAKE','Snake','1789047410036.png','classic','Move the snake and survive.'],['WHEEL','Wheel','1789047512563.png','classic','Choose your risk and spin.'],['ITEM UPGRADER','Item Upgrader','1789046990064.png','classic','Push your item upward.'],['CASES','Cases','1789046713766.png','classic','Open the case.'],['COINFLIP','Coinflip','1789047410036.png','multiplayer','Choose heads or tails.'],['PLINKO','Plinko','1789047583001.png','classic','Drop the ball through the pegs.']];

async function loadWagerRace(){
  const body=$('raceBody'); if(!body)return;
  try{
    const r=await api('/api/wager-race');
    body.innerHTML=(r.leaderboard||[]).length ? r.leaderboard.map((x,i)=>`<tr><td>${i+1}</td><td><span class="racePlayer"><img src="https://mc-heads.net/avatar/${encodeURIComponent(String(x.username).replace(/^\./,''))}/32"><b>${x.username}</b></span></td><td>${money(x.wagered)}</td><td>${x.bets}</td></tr>`).join('') : '<tr><td colspan="4">No completed wagers yet.</td></tr>';
  }catch(e){body.innerHTML='<tr><td colspan="4">Leaderboard unavailable.</td></tr>';}
}
function safeCloseFromBackdrop(e){if(e.target===e.currentTarget)closeModal(e.currentTarget.id)}

function toast(m,type=''){let t=$('toast');t.textContent=m;t.className='toast show '+type;clearTimeout(window.__t);window.__t=setTimeout(()=>t.className='toast',2600)}
function show(id){$(id).classList.remove('hidden');document.body.classList.add('lock')}function closeModal(id){$(id).classList.add('hidden');if(id==='gameModal'){if(currentState?.gameId)api('/api/game/cancel','POST',{gameId:currentState.gameId}).catch(()=>{});clearInterval(crashTimer);currentGame=currentFair=currentState=null}if(!document.querySelector('.modal:not(.hidden)'))document.body.classList.remove('lock')}
async function api(url,method='GET',body){const r=await fetch(url,{method,headers:{'Content-Type':'application/json',...(currentSession?{'x-donutmine-session':currentSession}:{}),...(staffSession?{'x-donutmine-staff':staffSession}:{})},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error('Server returned HTML instead of JSON. Restart server.js.')}if(!r.ok)throw Error(d.error||'Request failed');return d}
function updateUI(){const logged=!!currentUser;$('wallet').classList.toggle('hidden',!logged);$('navBalance').textContent=money(currentUser?.balance);$('gameBalance').textContent=money(currentUser?.balance);$('profileText').textContent=logged?currentUser.username:'CONNECT';$('profileSkin').classList.toggle('hidden',!logged);if(logged)$('profileSkin').src='https://mc-heads.net/avatar/'+encodeURIComponent(String(currentUser.username).replace(/^\./,''))+'/64';}
function renderGames(filter='all'){let g=$('gamesGrid');g.innerHTML='';GAMES.filter(x=>filter==='all'||x[3]===filter).forEach((x,i)=>{let b=document.createElement('button');b.className='gameCard';b.innerHTML=`<div class="thumb"><img src="/assets/games/${x[2]}"><span>${String(i+1).padStart(2,'0')}</span><strong>PLAY ↗</strong></div><div class="gameInfo"><b>${x[1]}</b><small>${x[4]}</small></div>`;b.onclick=()=>openGame(x);g.appendChild(b)})}
async function startLogin(){let u=$('minecraftUsername').value.trim();if($('bedrockToggle')?.checked&&!u.startsWith('.'))u='.'+u;if(!/^\.?[A-Za-z0-9_]{3,16}$/.test(u))return toast('Invalid Minecraft username','error');try{const r=await api('/api/auth/start','POST',{username:u,minecraftUsername:u,player:u});pendingAuthId=r.id||r.requestId||r.authId;$('loginStatus').textContent='Waiting for exact payment…';$('loginPaymentArea').classList.remove('hidden');$('loginCmd').textContent=r.command||`/pay ${r.receiver||'ZynqelYT'} ${r.amount}`;clearInterval(loginTimer);loginTimer=setInterval(pollLogin,1500);pollLogin()}catch(e){$('loginStatus').textContent=e.message;toast(e.message,'error')}}
async function pollLogin(){if(!pendingAuthId)return;try{const r=await api('/api/auth/status/'+encodeURIComponent(pendingAuthId));$('loginStatus').textContent=r.status==='confirmed'?'Payment confirmed — connected!':'Waiting for payment…';if(r.status==='confirmed'||r.verified){clearInterval(loginTimer);currentSession=r.session;localStorage.setItem('donutmine_session',currentSession);currentUser={username:r.username,balance:Number(r.balance||0)};updateUI();closeModal('loginModal');toast('Minecraft account connected','ok')}}catch(e){}}
async function createDeposit(){if(!currentUser)return show('loginModal');let amount=Number($('depositInput').value);if(!Number.isSafeInteger(amount)||amount<=0)return toast('Enter a valid amount','error');try{let r=await api('/api/deposit/start','POST',{amount});pendingDepositId=r.id;$('depositPanel').classList.remove('hidden');$('depositCmd').textContent=r.command||`/pay ${r.receiver||'ZynqelYT'} ${r.amount}`;$('depositAmount').textContent=money(r.amount);$('depositStatus').textContent='Waiting for payment…';clearInterval(depositTimer);depositTimer=setInterval(pollDeposit,1500)}catch(e){$('depositStatus').textContent=e.message;toast(e.message,'error')}}
async function pollDeposit(){if(!pendingDepositId)return;try{let r=await api('/api/deposit/status/'+encodeURIComponent(pendingDepositId));if(r.status==='confirmed'||r.verified){clearInterval(depositTimer);currentUser.balance=Number(r.balance);updateUI();$('depositStatus').textContent='Deposit confirmed.';toast('Deposit credited','ok')}}catch(e){}}
async function withdraw(){let amount=Number($('withdrawAmount').value);if(!Number.isSafeInteger(amount)||amount<=0)return toast('Enter a valid amount','error');try{let r=await api('/api/withdraw','POST',{amount});currentUser.balance=Number(r.balance);updateUI();$('withdrawStatus').textContent='Payout requested.';toast('Withdrawal sent','ok')}catch(e){$('withdrawStatus').textContent=e.message;toast(e.message,'error')}}
async function copyText(t){await navigator.clipboard.writeText(t);toast('Copied','ok')}
async function staffLogin(){try{const r=await api('/api/staff/login','POST',{email:$('staffEmail').value,password:$('staffPassword').value});staffSession=r.token;localStorage.setItem('donutmine_staff',staffSession);currentSession=r.playerSession||'';if(currentSession)localStorage.setItem('donutmine_session',currentSession);currentUser={username:'ZynqelYT',balance:Number(r.balance||0),isStaff:true};updateUI();await loadStaff();toast('Staff login successful as ZynqelYT','ok')}catch(e){$('staffStatus').textContent=e.message;toast(e.message,'error')}}
async function loadStaff(){if(!staffSession)return;try{const r=await api('/api/staff/me');if(r.username==='ZynqelYT'){currentUser={username:'ZynqelYT',balance:Number(currentUser?.balance||0),isStaff:true};updateUI()} $('staffStatus').textContent='Authenticated as '+r.email;$('staffEmailLabel').textContent=r.email;$('staffSkin').src='https://mc-heads.net/avatar/ZynqelYT/64';$('staffPanel').classList.remove('hidden');$('staffStats').textContent=`${r.stats.users} users • ${r.stats.gamesPlayed} games • ${money(r.stats.totalBalance)} total balance`;renderPromoCodes(r.promoCodes||[])}catch{localStorage.removeItem('donutmine_staff');staffSession=''}}
async function renderPromoCodes(codes){const box=$('promoList');if(!box)return;box.innerHTML=codes.length?codes.map(c=>`<div class="promoRow"><code>${c.code}</code><b>${money(c.reward)}</b><span>${c.uses}/${c.maxUses} used</span><button data-promo-delete="${encodeURIComponent(c.code)}">DELETE</button></div>`).join(''):'<div class="promoEmpty">No promo codes yet.</div>';box.querySelectorAll('[data-promo-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this promo code?'))return;try{await api('/api/staff/promo/delete','POST',{code:decodeURIComponent(b.dataset.promoDelete)});toast('Promo code deleted','ok');loadStaff()}catch(e){toast(e.message,'error')}})}
async function staffAddBalance(){
  const username=$('staffBalanceUser').value.trim();
  const amount=$('staffBalanceAmount').value.trim();
  if(!username||!amount)return $('staffBalanceStatus').textContent='Enter a username and amount.';
  try{
    const r=await api('/api/staff/balance/add','POST',{username,amount});
    $('staffBalanceStatus').textContent=`Added ${money(r.amount)} to ${r.username} • New balance ${money(r.balance)}`;
    $('staffBalanceUser').value='';
    $('staffBalanceAmount').value='';
    await loadStaff();
    toast(`Balance added to ${r.username}`,'ok');
  }catch(e){$('staffBalanceStatus').textContent=e.message;toast(e.message,'error')}
}
async function createPromoCode(){try{const custom=$('promoCodeInput').value.trim();const reward=Number($('promoRewardInput').value);const maxUses=Number($('promoLimitInput').value);const r=await api('/api/staff/promo/create','POST',{code:custom,reward,maxUses});$('promoCodeInput').value='';$('promoRewardInput').value='';$('promoLimitInput').value='';$('promoStatus').textContent=`Created ${r.code} • ${money(r.reward)} • ${r.maxUses} uses`;await loadStaff();toast('Promo code created','ok')}catch(e){$('promoStatus').textContent=e.message;toast(e.message,'error')}}
async function redeemPromo(){if(!currentUser)return show('loginModal');const code=$('promoRedeemInput').value.trim();if(!code)return toast('Enter a promo code','error');try{const r=await api('/api/promo/redeem','POST',{code});currentUser.balance=Number(r.balance);updateUI();$('promoRedeemStatus').textContent=`Redeemed ${r.code} — +${money(r.reward)}`;toast('Promo reward credited','ok');$('promoRedeemInput').value=''}catch(e){$('promoRedeemStatus').textContent=e.message;toast(e.message,'error')}}
async function staffLogout(){await api('/api/staff/logout','POST').catch(()=>{});localStorage.removeItem('donutmine_staff');localStorage.removeItem('donutmine_session');staffSession='';currentSession='';if(currentUser?.isStaff){currentUser=null;updateUI()}$('staffPanel').classList.add('hidden');$('staffStatus').textContent='';toast('Staff logged out')}
async function ensureFair(game){let r=await api('/api/fair/commit','POST',{game,clientSeed:crypto.randomUUID()});currentFair=r;$('liveHash').textContent=r.serverSeedHash;return r}
function betPanel(extra=''){return `<aside class="betPanel"><div class="betTitle">YOUR BET</div><div class="betInput"><button data-betminus>−</button><span>$</span><input id="bet" value="10" inputmode="numeric"><button data-betplus>+</button></div><div class="quick"><button data-half>½</button><button data-min>MIN</button><button data-double>2×</button><button data-max>MAX</button></div>${extra}<button id="playAction" class="playBtn">START ROUND <b>↗</b></button><div id="resultBox" class="result hidden"><i id="resultIcon">×</i><div><b id="resultTitle">ROUND LOST</b><small id="resultDetail"></small></div><strong id="resultPayout">-$10</strong></div></aside>`}
function wireBet(){let inp=$('bet');if(!inp)return;const q=s=>document.querySelector(s);const clamp=()=>{let v=Math.max(1,Math.floor(Number(inp.value)||1));if(currentUser)v=Math.min(v,Math.floor(currentUser.balance));inp.value=v};const bind=(sel,fn)=>{const el=q(sel);if(el)el.onclick=fn};bind('[data-betminus]',()=>{inp.value=Math.max(1,Number(inp.value)-1)});bind('[data-betplus]',()=>{inp.value=Number(inp.value)+1;clamp()});bind('[data-half]',()=>{inp.value=Math.max(1,Math.floor(Number(inp.value)/2))});bind('[data-double]',()=>{inp.value=Number(inp.value)*2;clamp()});bind('[data-min]',()=>inp.value=1);bind('[data-max]',()=>inp.value=currentUser?Math.floor(currentUser.balance):1);inp.onchange=clamp}
async function begin(game){if(currentUser?.isStaff)return toast('Staff accounts cannot play games. Connect a Minecraft player account.','error'),false;if(!currentUser){show('loginModal');return false}let bet=Math.floor(Number($('bet').value)||0);if(!bet||bet>currentUser.balance)return toast('Insufficient balance','error'),false;try{currentFair=await ensureFair(game);let r=await api('/api/game/start','POST',{game,bet,commitId:currentFair.id});currentState=r.state;return true}catch(e){toast(e.message,'error');return false}}
function result(r){let box=$('resultBox');box.className='result '+(r.win?'win':r.tie?'tie':'loss');$('resultIcon').textContent=r.win?'✓':r.tie?'=':'×';$('resultTitle').textContent=r.win?'YOU WON':r.tie?'TIE ROUND':'ROUND LOST';$('resultDetail').textContent=r.detail||'';$('resultPayout').textContent=r.win?'+'+money(r.payout):r.tie?'RETURN '+money(r.payout):'-'+money($('bet').value);if(currentUser){currentUser.balance=Number(r.balance);updateUI()}}
async function settleSimple(value,extra={}){if(!currentState){if(!await begin(currentGame))return}try{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'play',value,...extra});result(r)}catch(e){toast(e.message,'error')}}
function gameLayout(arena,controls=''){return `<div class="gameLayout"><section class="arena">${arena}</section>${betPanel(controls)}</div>`}
function openGame(g){currentGame=g[0];currentChoice=null;currentState=null;clearInterval(crashTimer);$('gameKicker').textContent=g[0];$('gameTitle').textContent=g[1];show('gameModal');$('gameBody').innerHTML=gameLayout('<div class="bootGame"><div class="bootSpinner"></div><b>Opening '+g[1]+'…</b></div>');Promise.resolve().then(()=>renderGame(g[0])).catch(e=>{console.error(e);$('gameBody').innerHTML=gameLayout('<div class="gameError"><b>GAME LOAD ERROR</b><span>'+String(e.message||e)+'</span><button class="actionBtn" onclick="openGame(GAMES.find(x=>x[0]===currentGame))">RETRY</button></div>');wireBet();});}
function commonButton(text,cls='',attr=''){return `<button class="actionBtn ${cls}" ${attr}>${text}</button>`}
async function renderGame(game){let a=document.querySelector('.arena');if(!a)throw new Error('Game arena was not created.');
if(game==='MINES'){a.innerHTML='<div class="gameLabel">MINES • 5 × 5</div><div class="mineTop"><b id="mineMulti">1.00×</b><span id="mineSafe">0 SAFE</span></div><div id="mineGrid" class="mineGrid">'+Array(25).fill('<button>?</button>').join('')+'</div><button id="cashout" class="cashBtn hidden">CASH OUT <b id="cashValue">$0</b></button>';wireBet();$('playAction').onclick=async()=>{if(!await begin(game))return; $('playAction').disabled=true;toast('Pick tiles to play');};document.querySelectorAll('#mineGrid button').forEach((b,i)=>b.onclick=async()=>{if(!currentState)return;try{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'reveal',value:i});if(r.action==='safe'){b.classList.add('safe');b.textContent='◆';$('mineMulti').textContent=Number(r.multiplier).toFixed(2)+'×';$('mineSafe').textContent=r.revealed.length+' SAFE';$('cashout').classList.remove('hidden');$('cashValue').textContent=money(Number($('bet').value)*Math.max(2,r.multiplier))}else result(r)}catch(e){toast(e.message,'error')}});$('cashout').onclick=async()=>{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'cashout'});result(r)};return}
if(game==='TOWER'){a.innerHTML='<div class="gameLabel">TOWER • CLIMB</div><div id="tower" class="tower">'+Array(8).fill(0).map((_,i)=>`<div class="floor" data-floor-row="${i}"><small>F${i+1}</small>${[0,1,2].map(j=>`<button data-floor="${i}" data-lane="${j}" disabled>◆</button>`).join('')}</div>`).join('').reverse()+'</div><div class="towerBottom"><b id="towerMulti">1.00×</b><button id="towerCash" class="cashBtn" disabled>CASH OUT</button></div>';wireBet();const enableTowerFloor=(floor)=>{document.querySelectorAll('[data-lane]').forEach(x=>{x.disabled=Number(x.dataset.floor)!==floor||!!x.classList.contains('safe')});const row=document.querySelector(`[data-floor-row="${floor}"]`);if(row)row.classList.add('current')};$('playAction').onclick=async()=>{if(await begin(game)){$('playAction').disabled=true;enableTowerFloor(0);toast('Choose a block on floor 1')}};document.querySelectorAll('[data-lane]').forEach(b=>b.onclick=async()=>{if(!currentState||Number(b.dataset.floor)!==currentState.floor)return;try{b.disabled=true;let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'choose',value:Number(b.dataset.lane)});if(r.action==='safe'){b.classList.add('safe');$('towerMulti').textContent=Number(r.multiplier).toFixed(2)+'×';currentState.floor=Number(r.floor);if(currentState.floor>=currentState.maxFloor){result(r);return}$('towerCash').disabled=false;enableTowerFloor(currentState.floor);toast('Floor '+(currentState.floor+1)+' — choose a block')}else{result(r)}}catch(e){b.disabled=false;toast(e.message,'error')}});$('towerCash').onclick=async()=>{if(!currentState||!currentState.floor)return toast('Climb at least one floor first','error');try{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'cashout'});result(r)}catch(e){toast(e.message,'error')}};return}
if(game==='CRASH'){a.innerHTML='<div class="crashArena"><div class="crashHeader"><b id="crashMult">1.00×</b><span id="crashStatus">WAITING FOR START</span></div><div class="chart"><div class="chartline"></div><div id="rocket">🚀</div><div class="axis">1×　2×　3×　5×　10×</div></div><div class="crashHistory"><span>LIVE</span><i>1.28×</i><i>2.44×</i><i>1.09×</i><i>4.81×</i></div></div>';wireBet();$('playAction').onclick=async()=>{if(!currentState){if(!await begin(game))return;$('playAction').textContent='CASH OUT ↗';$('crashStatus').textContent='ROCKET IS RISING';clearInterval(crashTimer);crashTimer=setInterval(async()=>{try{let q=await api('/api/game/status/'+currentState.gameId);let m=q.multiplier||1;$('crashMult').textContent=Number(m).toFixed(2)+'×';$('rocket').style.left=Math.min(92,5+Math.log(m)*30)+'%';$('rocket').style.bottom=Math.min(78,8+Math.log(m)*22)+'%';if(q.crashed){clearInterval(crashTimer);$('crashStatus').textContent='CRASHED';result(q.result);$('playAction').textContent='START ROUND ↗';currentState=null}}catch(e){}} ,70)}else{let m=Number(($('crashMult').textContent||'1').replace('×',''));try{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'cashout',value:m});clearInterval(crashTimer);result(r);$('crashStatus').textContent='CASHED OUT';$('playAction').textContent='START ROUND ↗';currentState=null}catch(e){toast(e.message,'error')}}};return}
if(game==='BLACKJACK'){a.innerHTML='<div class="table blackjack"><div class="dealer"><small>DEALER</small><div id="dealerCards" class="cards"></div><b id="dealerScore"></b></div><div class="felt">♠ ♥ ♦ ♣</div><div class="player"><small>YOU</small><div id="playerCards" class="cards"></div><b id="playerScore"></b></div></div>';wireBet();$('playAction').onclick=async()=>{if(await begin(game)){drawBJ(currentState);$('playAction').classList.add('hidden');a.insertAdjacentHTML('beforeend','<div class="bjActions"><button data-bj="hit">HIT</button><button data-bj="stand">STAND</button><button data-bj="double">DOUBLE</button></div>');document.querySelectorAll('[data-bj]').forEach(b=>b.onclick=async()=>{let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:b.dataset.bj});if(r.player){currentState.player=r.player;drawBJ(r)}else result(r)})}};return}
if(game==='KENO'){a.innerHTML='<div class="kenoHead"><b id="kenoHits">SELECT 10 NUMBERS</b><span id="kenoDraw"></span></div><div id="kenoGrid" class="kenoGrid">'+Array.from({length:40},(_,i)=>`<button>${i+1}</button>`).join('')+'</div>';wireBet();document.querySelectorAll('.kenoGrid button').forEach(b=>b.onclick=()=>{if(b.classList.contains('sel'))b.classList.remove('sel');else if(document.querySelectorAll('.kenoGrid .sel').length<10)b.classList.add('sel');$('kenoHits').textContent=document.querySelectorAll('.kenoGrid .sel').length+' / 10'});$('playAction').onclick=async()=>{let chosen=[...document.querySelectorAll('.kenoGrid .sel')].map(x=>Number(x.textContent));if(chosen.length!==10)return toast('Pick exactly 10 numbers','error');await settleSimple(chosen)};return}
if(game==='COINFLIP'){a.innerHTML='<div class="coinArena"><div id="coin" class="coin">🍩</div><div class="coinChoices"><button data-side="HEADS">HEADS</button><button data-side="TAILS">TAILS</button></div></div>';wireBet();document.querySelectorAll('[data-side]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-side]').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');currentChoice={side:b.dataset.side};$('playAction').textContent='FLIP COIN ↗'});$('playAction').onclick=async()=>{if(!currentChoice?.side)return toast('Choose heads or tails','error');if(!currentState&&!(await begin(game)))return;$('coin').classList.add('flip');await wait(900);$('coin').classList.remove('flip');await settleSimple(currentChoice.side)};return}
if(game==='HI-LO'){a.innerHTML='<div class="hilo"><div class="bigCard" id="currentCard">?</div><div class="hiloChoices"><button data-call="HIGH">HIGHER</button><button data-call="LOW">LOWER</button></div></div>';wireBet();document.querySelectorAll('[data-call]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-call]').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');currentChoice={call:b.dataset.call};$('playAction').textContent='REVEAL CARD ↗'});$('playAction').onclick=async()=>{if(!currentChoice?.call)return toast('Choose higher or lower','error');await settleSimple(currentChoice.call)};return}
if(game==='DICE'){a.innerHTML='<div class="diceArena"><div class="diceBig" id="diceFace">?</div><div class="targetRow"><label>TARGET <input id="diceTarget" type="range" min="1" max="99" value="50"></label><b id="diceTargetText">50</b><button id="diceMode">ROLL OVER</button></div></div>';wireBet();$('diceTarget').oninput=()=>{$('diceTargetText').textContent=$('diceTarget').value};$('diceMode').onclick=()=>{$('diceMode').textContent=$('diceMode').textContent==='ROLL OVER'?'ROLL UNDER':'ROLL OVER'};$('playAction').onclick=async()=>{if(!await begin(game))return;for(let i=0;i<14;i++){ $('diceFace').textContent=(Math.random()*100).toFixed(1);await wait(35)}let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'play',value:Number($('diceTarget').value),over:$('diceMode').textContent==='ROLL OVER'});$('diceFace').textContent=(r.detail.match(/Rolled ([\d.]+)/)||[])[1]||'?';result(r)};return}
if(game==='RUSSIAN ROULETTE'){a.innerHTML='<div class="gunArena"><div id="gun" class="gun">🔫</div><p>Choose one of six chambers.</p><div class="chambers">'+[1,2,3,4,5,6].map(i=>`<button data-chamber="${i}">${i}</button>`).join('')+'</div></div>';wireBet();document.querySelectorAll('[data-chamber]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-chamber]').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');currentChoice={chamber:Number(b.dataset.chamber)};$('playAction').textContent='PULL TRIGGER ↗'});$('playAction').onclick=async()=>{if(!currentChoice?.chamber)return toast('Choose a chamber','error');if(!currentState&&!(await begin(game)))return;$('gun').classList.add('shake');await wait(650);$('gun').classList.remove('shake');await settleSimple(currentChoice.chamber)};return}
if(game==='DONUT ROULETTE'){a.innerHTML='<div class="wheelArena"><div id="roulette" class="roulette">'+Array.from({length:16},(_,i)=>`<i>${i+1}</i>`).join('')+'</div><div class="pointer">▼</div></div>';wireBet();$('playAction').onclick=async()=>{if(!await begin(game))return;$('roulette').style.transform=`rotate(${1440+Math.random()*720}deg)`;await wait(1500);await settleSimple(1)};return}
if(game==='WHEEL'){a.innerHTML='<div class="wheelArena"><div id="wheel" class="gameWheel"><span>1.2×</span><span>2×</span><span>5×</span><span>10×</span><span>1.5×</span><span>3×</span></div><div class="pointer">▼</div></div>';wireBet();$('playAction').onclick=async()=>{if(!await begin(game))return;$('wheel').style.transform=`rotate(${1800+Math.random()*720}deg)`;await wait(1300);await settleSimple(1)};return}
if(game==='PLINKO'){a.innerHTML='<div class="plinko"><div id="ball" class="ball">●</div><div class="pegs">'+Array.from({length:55},(_,i)=>`<i style="left:${10+(i%11)*8}% ;top:${12+Math.floor(i/11)*15}%"></i>`).join('')+'</div><div class="slots"><b>0.5×</b><b>1×</b><b>2×</b><b>5×</b><b>10×</b></div></div>';wireBet();$('playAction').onclick=async()=>{if(!await begin(game))return;let b=$('ball');b.style.top='4%';b.style.left='50%';for(let i=0;i<10;i++){await wait(90);b.style.top=(8+i*8)+'%';b.style.left=(15+Math.random()*70)+'%'}await settleSimple(1)};return}
if(game==='SNAKE'){a.innerHTML='<div class="snakeArena"><div class="snakeScore">SCORE <b id="snakeScore">0</b></div><div id="snakeBoard" class="snakeBoard"></div><div class="snakeKeys"><button data-m="up">▲</button><button data-m="left">◀</button><button data-m="down">▼</button><button data-m="right">▶</button></div></div>';wireBet();let pos=12;function paint(){let board=$('snakeBoard');board.innerHTML=Array(25).fill(0).map((_,i)=>`<i class="${i===pos?'snake':''}"></i>`).join('')}paint();document.querySelectorAll('[data-m]').forEach(b=>b.onclick=async()=>{if(!currentState) {if(!await begin(game))return;$('playAction').disabled=true}let m=b.dataset.m;pos=Math.max(0,Math.min(24,pos+(m==='left'?-1:m==='right'?1:m==='up'?-5:5)));$('snakeScore').textContent=Number($('snakeScore').textContent)+1;paint()});$('playAction').onclick=async()=>{if(!currentState){if(!await begin(game))return;$('playAction').disabled=true}await wait(200);await settleSimple(Number($('snakeScore').textContent))};return}
if(['LIMBO','STRIP MINE','CASE BATTLES','ITEM UPGRADER','CASES'].includes(game)){a.innerHTML=`<div class="genericInteractive"><div class="bigIcon">${game==='LIMBO'?'↗':game==='STRIP MINE'?'⛏':game==='CASE BATTLES'?'⚔':game==='ITEM UPGRADER'?'⬆':'📦'}</div><div id="genericStage" class="genericStage">READY</div><div class="genericChoices">${game==='LIMBO'?'<label>TARGET <input id="limboTarget" type="number" min="1.01" step="0.01" value="2"></label>':game==='ITEM UPGRADER'?'<button data-risk="low">LOW RISK</button><button data-risk="high">HIGH RISK</button>':game==='CASES'?'<button data-case="1">OPEN CASE</button><button data-case="2">PREMIUM CASE</button>':'<button data-action="go">PLAY</button>'}</div></div>`;wireBet();document.querySelectorAll('.genericChoices button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.genericChoices button').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');currentChoice=b.dataset});$('playAction').onclick=async()=>{if(!await begin(game))return;$('genericStage').classList.add('pulse');await wait(900);$('genericStage').textContent='REVEAL';await wait(300);let v=game==='LIMBO'?Number($('limboTarget').value):currentChoice?.risk||currentChoice?.case||1;let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'play',value:v});result(r)};return}
// Remaining interactive roulette-like game
if(game==='KENO')return;
a.innerHTML='<div class="genericInteractive"><div class="bigIcon">🎮</div><div class="genericStage">READY</div></div>';wireBet();$('playAction').onclick=async()=>{if(await begin(game)){await wait(800);let r=await api('/api/game/action','POST',{gameId:currentState.gameId,action:'play',value:1});result(r)}}}
function drawBJ(s){$('playerCards').innerHTML=(s.player||[]).map(c=>`<span>${c}</span>`).join('');$('dealerCards').innerHTML=(s.dealer||[]).map(c=>`<span>${c}</span>`).join('');$('playerScore').textContent=s.playerValue||''}
$('heroPlay').onclick=()=>document.querySelector('#games').scrollIntoView({behavior:'smooth'});$('heroLogin').onclick=()=>show('loginModal');$('loginOpen').onclick=()=>currentUser?toast('Connected as '+currentUser.username):show('loginModal');$('depositOpen').onclick=()=>currentUser?.isStaff?toast('Staff accounts cannot deposit.'):currentUser?show('depositModal'):show('loginModal');$('withdrawOpen').onclick=()=>currentUser?.isStaff?toast('Staff accounts cannot withdraw.'):currentUser?show('withdrawModal'):show('loginModal');$('loginContinue').onclick=startLogin;$('staffContinue').onclick=staffLogin;$('staffLogout').onclick=staffLogout;$('promoCreateBtn').onclick=createPromoCode;$('staffBalanceBtn').onclick=staffAddBalance;$('promoRefresh').onclick=loadStaff;$('promoRedeemBtn').onclick=redeemPromo;$('mcTab').onclick=()=>{$('mcTab').classList.add('active');$('staffTab').classList.remove('active');$('mcAuth').classList.remove('hidden');$('staffAuth').classList.add('hidden');$('authTitle').textContent='Sign in with Minecraft';$('authSubtitle').textContent='Connect your DonutSMP name to start playing.'};$('staffTab').onclick=()=>{$('staffTab').classList.add('active');$('mcTab').classList.remove('active');$('staffAuth').classList.remove('hidden');$('mcAuth').classList.add('hidden');$('authTitle').textContent='Staff login';$('authSubtitle').textContent='Restricted dashboard access.'};$('depositContinue').onclick=createDeposit;$('withdrawContinue').onclick=withdraw;$('copyLogin').onclick=()=>copyText($('loginCmd').textContent);$('copyDeposit').onclick=()=>copyText($('depositCmd').textContent);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=(e)=>{e.preventDefault();e.stopPropagation();closeModal(b.dataset.close)});document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',safeCloseFromBackdrop));document.addEventListener('keydown',e=>{if(e.key==='Escape'){const open=document.querySelector('.modal:not(.hidden)');if(open)closeModal(open.id)}});$('raceRefresh').onclick=loadWagerRace;document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGames(b.dataset.filter)});async function restore(){if(staffSession){await loadStaff();return}if(!currentSession)return;try{let r=await api('/api/me');currentUser=r.user||r;currentUser.balance=Number(currentUser.balance||0);updateUI()}catch{localStorage.removeItem('donutmine_session');currentSession=''}}renderGames();updateUI();restore();loadStaff();loadWagerRace();
